# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Caffey
email: briancaffey2010@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://briancaffey.github.io" # the base hostname & protocol for your site
twitter_username: briancaffey
github_username: briancaffey
gitlab_username: briancaffey
linkedin_username: brian-caffey-06b22a18
linkedin_name: Brian Caffey
so_username: briancaffey
so_link: 6084948/briancaffey
steemit_name: mrbrian
steemit_username: mrbrian

# Build settings
markdown: kramdown
highlighter: rouge

repository: briancaffey.github.io

#gems:
#  - jekyll-assets

collections:
  projects:
    output: true
    permalink: /:collection/:name
